### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by kdb424** [inlets/mixctl#16]
**Who is this for?**
Personal

**Why do you need this?**
Some applications require UDP support such as VOIP

**Is your feature request related to a problem? Please describe.**
Mixctl has been a great load balancer and reverse proxy for many of my services in learning and deploying personal services. The vast majority of services are TCP, but I've run into several cases where UDP support was needed, such as, but not limited to, VOIP services. This leaves mixctl generally useful, but requires reaching for different tooling depending on the service.

**Describe the solution you'd like**
UDP support added to allow for this to be a simple tool for almost every possible simple case reverse proxy/load balancer.

**Describe alternatives you've considered**
[tinyPortMapper](https://github.com/wangyu-/tinyPortMapper) is far less convenient, but does seem to do the job of both in terms of simple solutions that aren't haproxy or nginx

**Comment by alexellis** [comment]
Hi @kdb424 mixctl is meant only for inlets subscribers and not as a generic free tool for anyone to use.

inlets is very unlikely to support UDP due to the many nuances and due to tunnelling UDP over TCP being generally accepted as unwise.

That said we may take a look into a reverse proxy for UDP at some point in the future for inlets subscribers. Let me know if that would be of interest and what kind of VOIP protocols you're considering.

For now, I'll close this on mixctl as not planned.

Alex
